version: '3'
services:
  cypress_test:
      image: cypress-compose
      build: 
        context: .
        dockerfile: ./Dockerfile
      volumes:
        - ./dockerReports:/app/cypress/results
        - ./dockerReports:/app/mochawesome-reports
      command: ["npm", "run", "cypress:e2e"]