version: '3'
services:
  cypress_test:
      image: cypress
      build: 
        context: .
        dockerfile: ./Dockerfile
      volumes:
        - ./dockerReports:/app/cypress/results
        - ./dockerReports:/app/mochawesome-report
      command: ["npm", "run", "cypress:e2e"]